[build-system]
requires = ["setuptools>=45", "setuptools_scm>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "pipeline/_version.py"

[tool.pytest.ini_options]
addopts = ["--cov"]

[tool.coverage.run]
branch = true
source = ["pypeline"]
omit = ["pypeline/tests/*"]
